### ISSUE TITLE
v 1.1.1 still disappears for me

### ISSUE THREAD

**Issue by fribse** [custom-cards/aftership-card#12]
**Version of the cusom_component**
1.1.1

**Describe the bug**
The card goes invisible if a package doesn't have a location it seems.

**log**
Not sure what logfile you refer to.
The aftership sensor shows this
{
  "attribution": "Information provided by AfterShip",
  "pending": 1,
  "trackings": [
    {
      "name": "Trykknap",
      "tracking_number": "LX744882759NL",
      "slug": "postnl-international",
      "link": "https://track.aftership.com/postnl-international/LX744882759NL",
      "last_update": "2019-08-27T21:11:27+00:00",
      "expected_delivery": null,
      "status": "Pending",
      "last_checkpoint": "Shipment pending"
    }
  ],
  "unit_of_measurement": "packages",
  "friendly_name": "aftership",
  "icon": "mdi:package-variant-closed"
}

**Comment by iantrich** [comment]
Looks like I messed up the tagging of 1.1.1 release. Try 1.1.3, please.

**Comment by fribse** [comment]
Looks much better!
Though some scaling is failing a bit:
![2019-08-28_1154](https://user-images.githubusercontent.com/13660621/63845746-bf14ec00-c98a-11e9-8002-853ff5ad213e.png)
When the window is wider, there is no problem.
