### ISSUE TITLE
Cannot install via HACS

### ISSUE THREAD

**Issue by alesurli** [custom-cards/aftership-card#13]
Hello,
i can't install plugin with homeassistant release 0.101.2 (docker version)

From home-assistant.log i have the following entries when trying to install:

2019-11-11 16:48:47 ERROR (MainThread) [hacs.http] No repository found with ID example.png

**Comment by iantrich** [comment]
I have no idea what that means. Any thoughts @ludeeus ?

**Comment by ludeeus** [comment]
That is a result of images using a relative path in the readme, HACS does not have access to the repository and tries to resolve it.

Will not block/halt/stop installation, you get that on the render of the info, not during installation.

**Comment by alesurli** [comment]
I had exactly this message when i press install. 
Also, in the dir www/community doesn't appear the folder of the plugin.

**Comment by iantrich** [comment]
Just tried on my production server and can confirm that it is not installing as expected. I don't see any errors, however, in my logs.
