### ISSUE TITLE
Delivery status misaligned and not cropped

### ISSUE THREAD

**Issue by AlexKalopsia** [custom-cards/aftership-card#17]
**Release with the issue:**

**Last working release (if known):** 1.1.9

**Browser and Operating System:** Firefox/Chrome, WIn10

**Description of problem:**
The card works and pulls the data correctly, but the styling is completely off on my end. 
The status (Delivered, In Transit...) is not aligned to the right edge of the card, and sometimes it even goes further outside of it (instead of cropping the text)

Reference image: https://imgur.com/a/Cub23jE

**Additional information:**
- Text position is not affected by browser window size
- I am using a custom sensor in order to address this bug (https://github.com/home-assistant/home-assistant/issues/25481). In the thread you can check my edit. The bug has an out of range array that normally makes the sensor not work. My temp fix addresses that problem. 

Thanks for the card!

**Comment by iantrich** [comment]
Yeah, didn't spend too much time on styling. PRs welcome

**Comment by filikun** [comment]
Any update on this? Just added this myself and with long tracking numbers it looks pretty bad to be honest. Maybe just skip the tracking numbers under the shipment name?

**Comment by iantrich** [comment]
> PRs welcome

**Comment by iantrich** [comment]
should be fixed in 1.2.1
