### ISSUE TITLE
add tracking not working

### ISSUE THREAD

**Issue by poudenes** [custom-cards/aftership-card#19]
Hi There,

When I add a tracking in Aftership portal I see it back in the card.
When I add a tracking from the card it doesn't show in Aftership portal or in the card 

What can this be?

**Comment by rabeliyo** [comment]
Same situation

**Comment by iantrich** [comment]
Can you try the service call itself in Developer Tools > Services

**Comment by iantrich** [comment]
closing with no response

**Comment by myntath** [comment]
I'm also having this issue. I have tried calling the aftership.add_tracking in developer tools and it will work but only if I include the 'slug' field. The card only lets me include the title and tracking number so I suspect this might be causing my issue.

**Comment by outlooknerd** [comment]
Still the case. Apparently Aftership now requires the slug parameter to be filled while submitting a new parcel to track. The service works perfectly from Developer Tools, so the solution would be to add the slug field to the Aftership card and pass along this information to the service.

**Comment by slinkymanbyday** [comment]
Added PR. in the meantime, feel free to use the version in my fork as a custom repo in HACS.
