### ISSUE TITLE
no tracking info displayed.

### ISSUE THREAD

**Issue by bennydente** [custom-cards/aftership-card#2]
Hi, i have latest (today get it) version of custom card.
I have this error 
![schermata 2019-01-16 alle 11 33 15](https://user-images.githubusercontent.com/22501791/51243363-a4a17b80-1982-11e9-8bce-b832692ae7b4.png)

**Comment by ludeeus** [comment]
Share the state + all attributes of the sensor.

**Comment by bennydente** [comment]
Here you are.

State: 1

attribution: Information provided by AfterShip
intransit: 1 
unit_of_measurement: packages 
friendly_name: aftership 
icon: mdi:package-variant-closed

**Comment by ludeeus** [comment]
That card is designed to work with the custom sensor.
<https://github.com/custom-components/sensor.custom_aftership>

It looks like you are using the official one?

**Comment by bennydente** [comment]
uups... Yes, I'm on official one. thanks. I change to custom one.
