### ISSUE TITLE
Screen on ios is messed up

### ISSUE THREAD

**Issue by stefancvetkovic** [custom-cards/aftership-card#20]
I installed and successfully connected my aftership account.
On my PC, it shows just fine, but on a ios homeasssitant companion it shows right white margin 
![image](https://user-images.githubusercontent.com/13699747/74164011-7775da00-4c23-11ea-9588-5bbd6ab6121e.png)

any thoughts?

**Comment by iantrich** [comment]
should be fixed in 1.2.1
