### ISSUE TITLE
Requesting a way to remove/hide old packages

### ISSUE THREAD

**Issue by mcaden** [custom-cards/aftership-card#21]
Delivered packages simply stay on the card, accumulating over time.

**Describe the solution you'd like**
- A configurable "expiration" where delivered packages would "expire" from the card X days after delivered.
- A way to delete packages from the card.

**Comment by iantrich** [comment]
Read the first few lines of the docs again...long press icon to remove

**Comment by mcaden** [comment]
🤦‍♂  My apologies.

**Comment by woobenjamin** [comment]
@iantrich - Is it possible to add an option to not display delivered  or expired packages?

**Comment by iantrich** [comment]
PRs welcome, but I will not be adding it myself
