### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by hessel-a** [custom-cards/aftership-card#23]
**Checklist:**

- [x ] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

Please update documentation that this needs a intergration and Api-key for this to work. Or link to https://www.home-assistant.io/integrations/aftership under "installation". 

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by iantrich** [comment]
It already does
![image](https://user-images.githubusercontent.com/1287159/76689974-b378d200-6609-11ea-9f99-3c5d28e90fe1.png)

**Comment by hessel-a** [comment]
Yes, eventually I found that too. But I think it should also be part of the installation instruction.

**Comment by iantrich** [comment]
PRs welcome
