### ISSUE TITLE
Aftership integration warning

### ISSUE THREAD

**Issue by mcv93us** [custom-cards/aftership-card#36]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**
v1.2.2
**Last working release (if known):**
v1.2.2
**Browser and Operating System:**
Google Chrome 96.0.4664.93 64Bit, Windows 10 Version 21H2 (Build 19044.1387)

**Description of problem:**
Good morning,
following the update of Home Assistant to version 2021.12.0 I found the following error in the log:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 14:35:01 (2 occurrences)
Last logged: 14:35:04

Detected integration that called async_timeout.timeout with loop keyword argument. The loop keyword argument is deprecated and calls will fail after Home Assistant 2022.2. Please report issue for aftership using this method at homeassistant/components/aftership/sensor.py, line 66: await aftership.get_trackings()
Detected integration that called async_timeout.timeout with loop keyword argument. The loop keyword argument is deprecated and calls will fail after Home Assistant 2022.2. Please report issue for aftership using this method at homeassistant/components/aftership/sensor.py, line 150: await self.aftership.get_trackings()

As this is a supplement that I use very often I would be sorry if it was unusable from February 2022.
I hope it can be fixed.

That warning shouldn't appear in the registry.
The method has been deprecated and will soon be no longer usable.

**Javascript errors shown in the web inspector (if applicable):**

```
none
```

**Additional information:**

**Comment by chpego** [comment]
Hi @mcv93us , it's not a problem in the aftership card, it's on the aftership integration.
And it's already fix here https://github.com/home-assistant/core/issues/63702 
You can close this issue ;)
