### ISSUE TITLE
Return "No ETA" and not 1st January 1970 when no ETA

### ISSUE THREAD

**Issue by SNoof85** [custom-cards/aftership-card#6]
**Is your feature request related to a problem? Please describe.**
When there's no ETA returned by aftership, the ETA is set to new date(Null) => 1 january 1970

**Describe the solution you'd like**
Print : No ETA

**Describe alternatives you've considered**
Ignoring...because it's not really an issue but just improvement

**Additional context**

**Comment by SNoof85** [comment]
Still there dear stalebot !

**Comment by iantrich** [comment]
I don't really have time to setup a test case for this but if you're able to try testing this change at https://github.com/custom-cards/aftership-card/blob/master/src/aftership-card.ts#L98

```
.title="${item.expected_delivery ? html`Expected Delivery: ${new Date(item.expected_delivery).toDateString()}` : html`No Date Set`}"
```

**Comment by SNoof85** [comment]
Hey, thx for your answer.

Not an expert in Typescript here so i don't really know how to apply this in the JS. Tried it and now i have `[object Object]` instead of wrong date. My attempt to apply this in JS file is probably wrong...

I have a test case here so i can still test :)

**Comment by iantrich** [comment]
Thanks! Fixed in https://github.com/custom-cards/aftership-card/releases/tag/1.1.2
